# Generated by Django 5.2.17 on 2026-10-06 13:36, then hand-edited:
#  * reference_id is renamed (not dropped) so existing ledger references survive,
#  * duplicate balance rows are merged before the identity constraints are created,
#  * the ledger becomes append-only through a PostgreSQL trigger.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.db.models import Count, Sum

LEDGER_TRIGGER_SQL = """
CREATE OR REPLACE FUNCTION inventory_stocktransaction_immutable() RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION 'inventory_stocktransaction is append-only (% blocked); record a compensating transaction', TG_OP
        USING ERRCODE = 'integrity_constraint_violation';
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS inventory_stocktransaction_immutable ON inventory_stocktransaction;
CREATE TRIGGER inventory_stocktransaction_immutable
    BEFORE UPDATE OR DELETE ON inventory_stocktransaction
    FOR EACH ROW EXECUTE FUNCTION inventory_stocktransaction_immutable();
"""

LEDGER_TRIGGER_REVERSE_SQL = """
DROP TRIGGER IF EXISTS inventory_stocktransaction_immutable ON inventory_stocktransaction;
DROP FUNCTION IF EXISTS inventory_stocktransaction_immutable();
"""


def guard_legacy_rows(apps, schema_editor):
    """Refuse to run if the migration would silently lose information."""
    StockReservation = apps.get_model("inventory", "StockReservation")
    StockTransaction = apps.get_model("inventory", "StockTransaction")
    if StockReservation.objects.filter(deleted_at__isnull=False).exists():
        raise RuntimeError(
            "Soft-deleted stock reservations exist. Release or cancel them explicitly before migrating; "
            "this migration removes reservation soft-delete in favour of status history."
        )
    if StockTransaction.objects.filter(quantity=0).exists():
        raise RuntimeError(
            "Zero-quantity stock transactions exist (created before quantity validation). "
            "Review them manually; history is never rewritten automatically."
        )


def map_source_type(apps, schema_editor):
    StockTransaction = apps.get_model("inventory", "StockTransaction")
    mapping = {"TRANSFER": "TRANSFER", "RESERVATION": "RESERVATION", "PROJECT": "PROJECT", "BOM_REVISION": "BOM_REVISION"}
    for legacy, typed in mapping.items():
        StockTransaction.objects.filter(reference_type__iexact=legacy).update(source_type=typed)
    StockTransaction.objects.filter(transaction_type__in=["RESERVATION", "RELEASE_RESERVATION"], source_type="MANUAL").update(
        source_type="RESERVATION"
    )


def merge_duplicate_balances(apps, schema_editor):
    """Merge balance rows sharing the same identity (possible before the NULL-safe constraints).

    Balances are summed into the oldest row. Transactions reference component/warehouse/location,
    not the balance row, so no history is touched.
    """
    InventoryItem = apps.get_model("inventory", "InventoryItem")
    dupes = (
        InventoryItem.objects.values("component_id", "warehouse_id", "location_id", "lot_batch")
        .annotate(n=Count("id"))
        .filter(n__gt=1)
    )
    for d in dupes:
        rows = InventoryItem.objects.filter(
            component_id=d["component_id"], warehouse_id=d["warehouse_id"],
            location_id=d["location_id"], lot_batch=d["lot_batch"],
        ).order_by("id")
        totals = rows.aggregate(on_hand=Sum("quantity_on_hand"), reserved=Sum("quantity_reserved"))
        keep = rows.first()
        keep.quantity_on_hand = totals["on_hand"]
        keep.quantity_reserved = totals["reserved"]
        keep.save(update_fields=["quantity_on_hand", "quantity_reserved"])
        rows.exclude(pk=keep.pk).delete()


def backfill_reservations(apps, schema_editor):
    InventoryItem = apps.get_model("inventory", "InventoryItem")
    StockReservation = apps.get_model("inventory", "StockReservation")
    for res in StockReservation.objects.filter(inventory_item__isnull=True):
        item = InventoryItem.objects.filter(
            component_id=res.component_id, warehouse_id=res.warehouse_id, location_id=res.location_id, lot_batch=""
        ).first()
        if item is not None:
            res.inventory_item = item
            res.save(update_fields=["inventory_item"])


class Migration(migrations.Migration):

    dependencies = [
        ('bom', '0001_initial'),
        ('components', '0001_initial'),
        ('inventory', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventoryitem',
            options={'ordering': ['component__internal_part_number', 'warehouse__code', 'location__code', 'lot_batch']},
        ),
        migrations.AlterModelOptions(
            name='stockreservation',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='stocktransaction',
            options={'ordering': ['-timestamp', '-id']},
        ),
        migrations.AlterModelOptions(
            name='warehouse',
            options={'ordering': ['code']},
        ),
        migrations.AlterModelOptions(
            name='warehouselocation',
            options={'ordering': ['warehouse__code', 'code']},
        ),
        migrations.AlterUniqueTogether(
            name='inventoryitem',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='warehouselocation',
            unique_together=set(),
        ),
        migrations.RunPython(guard_legacy_rows, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='stockreservation',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='stockreservation',
            name='deleted_by',
        ),
        # Keep existing reference data: reference_id becomes source_id; reference_type is mapped to
        # the typed source_type below before being dropped.
        migrations.RenameField(
            model_name='stocktransaction',
            old_name='reference_id',
            new_name='source_id',
        ),
        migrations.AddField(
            model_name='stockreservation',
            name='bom_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_reservations', to='bom.bomrevision'),
        ),
        migrations.AddField(
            model_name='stockreservation',
            name='inventory_item',
            field=models.ForeignKey(help_text='The exact stock row reserved against (null only for legacy rows).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='inventory.inventoryitem'),
        ),
        migrations.AddField(
            model_name='stockreservation',
            name='lot_batch',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='stockreservation',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='stockreservation',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_reservations', to='projects.project'),
        ),
        migrations.AddField(
            model_name='stockreservation',
            name='released_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='currency',
            field=models.CharField(blank=True, default='', max_length=3),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='lot_batch',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='quantity_on_hand_after',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='quantity_reserved_after',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='reference',
            field=models.CharField(blank=True, default='', help_text='Free-text document number', max_length=100),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='source_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='source_type',
            field=models.CharField(choices=[('MANUAL', 'Manual operation'), ('TRANSFER', 'Stock transfer'), ('RESERVATION', 'Stock reservation'), ('PROJECT', 'Project'), ('BOM_REVISION', 'BOM revision')], default='MANUAL', max_length=32),
        ),
        migrations.RunPython(map_source_type, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='stocktransaction',
            name='reference_type',
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='transfer_group_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='unit_cost',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_items', to='components.component'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_items', to='inventory.warehouselocation'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='lot_batch',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='maximum_stock',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='minimum_stock',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='quantity_on_hand',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='quantity_reserved',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='reorder_level',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_items', to='inventory.warehouse'),
        ),
        migrations.AlterField(
            model_name='stockreservation',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='components.component'),
        ),
        migrations.AlterField(
            model_name='stockreservation',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='inventory.warehouselocation'),
        ),
        migrations.AlterField(
            model_name='stockreservation',
            name='quantity',
            field=models.DecimalField(decimal_places=4, max_digits=14),
        ),
        migrations.AlterField(
            model_name='stockreservation',
            name='reference_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='stockreservation',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('RELEASED', 'Released'), ('CANCELLED', 'Cancelled')], db_index=True, default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='stockreservation',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='inventory.warehouse'),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_transactions', to='components.component'),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_transactions', to='inventory.warehouselocation'),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='performed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='quantity',
            field=models.DecimalField(decimal_places=4, max_digits=14),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='reason',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='transaction_type',
            field=models.CharField(choices=[('RECEIPT', 'Receipt'), ('ISSUE', 'Issue'), ('ADJUSTMENT_IN', 'Adjustment In'), ('ADJUSTMENT_OUT', 'Adjustment Out'), ('TRANSFER_OUT', 'Transfer Out'), ('TRANSFER_IN', 'Transfer In'), ('RESERVATION', 'Reservation'), ('RELEASE_RESERVATION', 'Release Reservation')], max_length=24),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_transactions', to='inventory.warehouse'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='warehouselocation',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='warehouselocation',
            name='parent_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sub_locations', to='inventory.warehouselocation'),
        ),
        migrations.AlterField(
            model_name='warehouselocation',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='locations', to='inventory.warehouse'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['component', 'warehouse'], name='inv_item_comp_wh_idx'),
        ),
        migrations.AddIndex(
            model_name='stockreservation',
            index=models.Index(fields=['component', 'status'], name='inv_res_comp_status_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransaction',
            index=models.Index(fields=['component', '-timestamp'], name='inv_txn_comp_ts_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransaction',
            index=models.Index(fields=['warehouse', '-timestamp'], name='inv_txn_wh_ts_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransaction',
            index=models.Index(fields=['source_type', 'source_id'], name='inv_txn_source_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransaction',
            index=models.Index(fields=['transaction_type', '-timestamp'], name='inv_txn_type_ts_idx'),
        ),
        migrations.RunPython(merge_duplicate_balances, migrations.RunPython.noop),
        migrations.RunPython(backfill_reservations, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='inventoryitem',
            constraint=models.UniqueConstraint(condition=models.Q(('location__isnull', False)), fields=('component', 'warehouse', 'location', 'lot_batch'), name='inv_item_identity_with_location'),
        ),
        migrations.AddConstraint(
            model_name='inventoryitem',
            constraint=models.UniqueConstraint(condition=models.Q(('location__isnull', True)), fields=('component', 'warehouse', 'lot_batch'), name='inv_item_identity_without_location'),
        ),
        migrations.AddConstraint(
            model_name='inventoryitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_on_hand__gte', 0)), name='inv_item_on_hand_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='inventoryitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_reserved__gte', 0)), name='inv_item_reserved_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='inventoryitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_reserved__lte', models.F('quantity_on_hand'))), name='inv_item_reserved_lte_on_hand'),
        ),
        migrations.AddConstraint(
            model_name='inventoryitem',
            constraint=models.CheckConstraint(condition=models.Q(('minimum_stock__gte', 0), ('reorder_level__gte', 0)), name='inv_item_levels_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='stockreservation',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='inv_reservation_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='stocktransaction',
            constraint=models.CheckConstraint(condition=models.Q(('quantity', 0), _negated=True), name='inv_txn_quantity_non_zero'),
        ),
        migrations.AddConstraint(
            model_name='stocktransaction',
            constraint=models.CheckConstraint(condition=models.Q(('unit_cost__isnull', True), ('unit_cost__gte', 0), _connector='OR'), name='inv_txn_unit_cost_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='warehouse',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('code',), name='inv_warehouse_code_unique_alive'),
        ),
        migrations.AddConstraint(
            model_name='warehouselocation',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('warehouse', 'code'), name='inv_location_code_unique_alive'),
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='deleted_by',
        ),
        migrations.RunSQL(LEDGER_TRIGGER_SQL, LEDGER_TRIGGER_REVERSE_SQL),
    ]
