# Generated by Django 5.2.17 on 2026-10-05 10:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user_email', models.CharField(blank=True, help_text='Preserved even if the user is removed.', max_length=254)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('RESTORE', 'Restore'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('LOGIN_FAILED', 'Login failed'), ('PASSWORD_CHANGE', 'Password change'), ('PERMISSION_CHANGE', 'Permission change'), ('FILE_UPLOAD', 'File upload'), ('FILE_DELETE', 'File delete'), ('STOCK_TRANSACTION', 'Stock transaction'), ('BOM_RELEASE', 'BOM release'), ('BOM_REVISION', 'BOM revision'), ('PURCHASE_APPROVAL', 'Purchase approval'), ('PURCHASE_ORDER', 'Purchase order')], db_index=True, max_length=32)),
                ('entity_type', models.CharField(db_index=True, help_text='app_label.model', max_length=100)),
                ('entity_id', models.CharField(blank=True, max_length=64)),
                ('entity_repr', models.CharField(blank=True, max_length=255)),
                ('old_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp', '-id'],
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='audit_entity_idx'), models.Index(fields=['user', '-timestamp'], name='audit_user_ts_idx')],
            },
        ),
    ]
