# Generated by Django 5.2.17 on 2026-10-05 10:15

import django.contrib.postgres.indexes
import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manufacturers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Needed by the component_search_trgm GIN index (trusted extension; DB owner may create it).
        TrigramExtension(),
        migrations.CreateModel(
            name='PartNumberSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=20, unique=True)),
                ('last_value', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(help_text='Part number prefix, e.g. IC-CAN', max_length=20, validators=[django.core.validators.RegexValidator('^[A-Z0-9]+(-[A-Z0-9]+)*$', 'Use upper-case letters, digits and single hyphens, e.g. IC-CAN.')])),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='components.category')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('internal_part_number', models.CharField(help_text='e.g. IC-CAN-00001. Never reused.', max_length=40, unique=True)),
                ('mpn', models.CharField(blank=True, max_length=100, verbose_name='manufacturer part number')),
                ('mpn_normalized', models.CharField(blank=True, db_index=True, editable=False, max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], db_index=True, default='ACTIVE', max_length=10)),
                ('lifecycle_status', models.CharField(choices=[('ACTIVE', 'Active'), ('NRND', 'Not recommended for new designs'), ('LAST_TIME_BUY', 'Last time buy'), ('OBSOLETE', 'Obsolete'), ('UNKNOWN', 'Unknown')], db_index=True, default='UNKNOWN', max_length=15)),
                ('is_rohs', models.BooleanField(blank=True, help_text='Null = unknown', null=True)),
                ('is_reach', models.BooleanField(blank=True, help_text='Null = unknown', null=True)),
                ('datasheet_url', models.URLField(blank=True, max_length=500)),
                ('datasheet_file', models.FileField(blank=True, max_length=255, upload_to='components/datasheets/')),
                ('image', models.ImageField(blank=True, max_length=255, upload_to='components/images/')),
                ('notes', models.TextField(blank=True)),
                ('search_document', models.TextField(blank=True, editable=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='components', to='components.category')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='components', to='manufacturers.manufacturer')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['internal_part_number'],
            },
        ),
        migrations.CreateModel(
            name='ComponentAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alias', models.CharField(max_length=150)),
                ('alias_normalized', models.CharField(db_index=True, editable=False, max_length=150)),
                ('alias_type', models.CharField(choices=[('ALTERNATE_MPN', 'Alternate MPN / ordering code'), ('LEGACY_PN', 'Legacy internal PN'), ('CUSTOMER_PN', 'Customer PN'), ('KICAD_VALUE', 'KiCad value / symbol name'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='components.component')),
            ],
            options={
                'ordering': ['alias'],
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(help_text='e.g. SOIC-8, 0603, LQFP-100', max_length=60)),
                ('mounting_type', models.CharField(choices=[('SMD', 'Surface mount'), ('THT', 'Through hole'), ('OTHER', 'Other')], default='SMD', max_length=10)),
                ('pin_count', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='component',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='components', to='components.package'),
        ),
        migrations.CreateModel(
            name='SpecificationDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(help_text='Stable machine key, e.g. capacitance')),
                ('name', models.CharField(max_length=100)),
                ('data_type', models.CharField(choices=[('STRING', 'Text'), ('INTEGER', 'Integer'), ('DECIMAL', 'Decimal'), ('BOOLEAN', 'Yes / No'), ('ENUM', 'Choice list')], max_length=10)),
                ('unit', models.CharField(blank=True, help_text='Base unit, e.g. F, Ω, V, W, %, KB', max_length=20)),
                ('use_si_prefix', models.BooleanField(default=False, help_text='Accept/display SI prefixes (p, n, µ, m, k, M) for DECIMAL values')),
                ('enum_choices', models.JSONField(blank=True, default=list, help_text='Allowed values for ENUM')),
                ('is_required', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('help_text', models.CharField(blank=True, max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='specification_definitions', to='components.category')),
            ],
            options={
                'ordering': ['category_id', 'sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ComponentSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value_string', models.CharField(blank=True, max_length=255)),
                ('value_integer', models.BigIntegerField(blank=True, null=True)),
                ('value_decimal', models.DecimalField(blank=True, decimal_places=18, max_digits=34, null=True)),
                ('value_boolean', models.BooleanField(blank=True, null=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='components.component')),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='values', to='components.specificationdefinition')),
            ],
            options={
                'ordering': ['definition__sort_order', 'definition__name'],
            },
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('code',), name='category_code_unique_alive'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('parent'), condition=models.Q(('deleted_at__isnull', True)), name='category_name_parent_unique_alive', nulls_distinct=False),
        ),
        migrations.AddConstraint(
            model_name='componentalias',
            constraint=models.UniqueConstraint(fields=('component', 'alias_normalized'), name='component_alias_unique'),
        ),
        migrations.AddConstraint(
            model_name='package',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), condition=models.Q(('deleted_at__isnull', True)), name='package_name_ci_unique_alive'),
        ),
        migrations.AddIndex(
            model_name='component',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('search_document'), name='gin_trgm_ops'), name='component_search_trgm'),
        ),
        migrations.AddIndex(
            model_name='component',
            index=models.Index(fields=['category', 'status'], name='component_cat_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='component',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), models.Q(('mpn_normalized', ''), _negated=True)), fields=('manufacturer', 'mpn_normalized'), name='component_mfr_mpn_unique_alive'),
        ),
        migrations.AddConstraint(
            model_name='specificationdefinition',
            constraint=models.UniqueConstraint(fields=('category', 'key'), name='specdef_category_key_unique'),
        ),
        migrations.AddIndex(
            model_name='componentspecification',
            index=models.Index(fields=['definition', 'value_decimal'], name='spec_def_decimal_idx'),
        ),
        migrations.AddIndex(
            model_name='componentspecification',
            index=models.Index(fields=['definition', 'value_integer'], name='spec_def_integer_idx'),
        ),
        migrations.AddIndex(
            model_name='componentspecification',
            index=models.Index(fields=['definition', 'value_string'], name='spec_def_string_idx'),
        ),
        migrations.AddConstraint(
            model_name='componentspecification',
            constraint=models.UniqueConstraint(fields=('component', 'definition'), name='component_spec_unique'),
        ),
    ]
