# Generated by Django 5.2.17 on 2026-10-06 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bom', '0001_initial'),
        ('components', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='bom',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='boms', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='bomrevision',
            name='bom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='bom.bom'),
        ),
        migrations.AddConstraint(
            model_name='bomitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='bom_item_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='bomrevision',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'RELEASED'), _negated=True), models.Q(('released_at__isnull', False), ('released_by__isnull', False)), _connector='OR'), name='bom_revision_released_has_releaser'),
        ),
    ]
